spring:
  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/flick_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucketName: flick-bucket